#!/usr/bin/env perl

use warnings;
use strict;

use Time::Local;

use FindBin;
use lib "$FindBin::Bin/lib";

use HTML::Calendar::Render;

my ($mday, $mon, $year) = (localtime)[3,4,5];

my $r = HTML::Calendar::Render->new;

$r->add_event(
    title => "a meeting",
    start => timelocal(0,0,10,$mday,$mon,$year),
    end   => timelocal(0,0,11,$mday,$mon,$year),
);

my $html = $r->render_month(timelocal(0,0,0,23,7,109), timelocal(0,0,0,29,7,109));
print $html;
