#!/usr/bin/env perl

use warnings;
use strict;

use Time::Local;

use FindBin;
use lib "$FindBin::Bin/lib";

use HTML::Calendar::Render;

my ($mday, $mon, $year) = (localtime)[3,4,5];

my $r = HTML::Calendar::Render->new;

$r->add_event(
    title    => "a meeting",
    location => "over there",
    text     => "louis is overpowered. discuss",
    start    => timelocal(0,0,10,$mday,$mon,$year),
    end      => timelocal(0,0,11,$mday,$mon,$year),
    id       => 1,
);
$r->add_event(
    title    => "another meeting",
    location => "behind you",
    text     => "pills here!",
    start    => timelocal(0,0,13,$mday,$mon,$year),
    end      => timelocal(0,0,14,$mday,$mon,$year),
    id       => 2,
);
$r->add_event(
    title    => "party day!",
    start    => timelocal(0,0,0,$mday+1,$mon,$year),
    allday   => 1,
);

print <<HTML
<html>
<head>
<link rel='stylesheet' type='text/css' href='test.css' />
</head>
<body>  
HTML
;

my $html = $r->render_days(timelocal(0,0,0,$mday,$mon,$year), 7);
#my $html = $r->render_month(timelocal(0,0,0,$mday,$mon,$year));
print $html;

print <<HTML
</body>
</html>
HTML
;
